owner: cdemi
repo: upptime

sites:
  - name: cdemi's Newsletter Archive
    url: https://newsletters.cdemi.io/
  - name: cdemi's Newsletter Curator
    url: https://newslettercurator.cdemi.io/health

status-website:
  cname: upptime.cdemi.io
  name: cdemi's Upptime
  
assignees:
  - cdemi
  
